# Site settings
title: LabCívico
email: prensa@ciudadanointeligente.org
description: Colaboración, tecnología e incidencia para el cambio social
baseurl: "//ciudadanointeligente.github.io/labcivico/" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  methodologies:
    output: true
  initiatives:
    output: true
  projects:
    output: true
  team:
    output: true