# site settings
title: LabCívico
email: prensa@ciudadanointeligente.org
description: 'Experimientos ciudadanos para el cambio social en la región'
baseurl: '//labcivico.org' #"//ciudadanointeligente.github.io/labcivico/"
basedomain: labcivico.org

# build settings
markdown: kramdown

collections:
  methodologies:
    output: true
  initiatives:
    output: true
  projects:
    output: true
  team:
    output: true